### ISSUE TITLE
Missing licensing information

### ISSUE THREAD

**Issue by lucasvr** [mkdashti/snappy-cuda#1]
Hello there, @mkdashti. First of all, nice project! I have just tested it on a few datasets and I was amazed at the decompression speed and GPU utilization. The code is also beautifully written and easy to follow.

Now, what I didn't find on the repository is the license under which the code is released. Is there any chance you might publish it on a library-friendly license such as the MIT or LGPL?

Thanks in advance and keep up the good work.

**Comment by mkdashti** [comment]
Thanks @lucasvr for your comments! As for the license, this code is my port of snappy-c which in turn is a port of Google's snappy. I wrote the code as part of our USENIX ATC'21 publication. I'm not an expert in licenses so I'm not sure if I can add an MIT or LGPL licence for the code if it was ported from another codebase which has a different license. For now I'll leave it license-less until I know if I can add a permissive license such as MIT.

**Comment by lucasvr** [comment]
Ah, I see! I just took a look at [Google's Snappy codebase](https://github.com/google/snappy/blob/master/COPYING) and it's licensed under the [BSD](https://opensource.org/licenses/BSD-3-Clause). Snappy-C is also distributed under the [same license](https://github.com/andikleen/snappy-c/blob/master/LICENSE). BSD is one of the most permissive licenses, actually, as it allows people to incorporate the code in proprietary projects (as long as the copyright notice is kept) or to link libraries licensed under the BSD to software distributed under different licenses.

**Comment by mkdashti** [comment]
Great! I've added a BSD license. I'd be interested in knowing how you incorporate the code and possibly collaborate on a project in the future!

**Comment by lucasvr** [comment]
Terrific, thanks a lot! I'll be working on making it an [I/O filter for HDF5](https://portal.hdfgroup.org/display/HDF5/Using+Compression+in+HDF5) -- will send you a PR as soon as it's in a good shape, just in case you'd like to see it merged. I'll read your ATC paper later today. I've been working on computational storage related research and at the very least you'll get a new citation :-)
